### ISSUE TITLE
Collections — Lists

### ISSUE THREAD

**Issue by chharvey** [chharvey/counterpoint#77]
# Features
- [x] new generic type syntax: `List.<T>`
- [x] new explicit type syntax `T[]`
- [x] new constructor syntax: `List.<T>([a, b, c])`, takes an optional tuple arg
	- allows empty list
- no literal syntax

# TODO
- [x] type syntaxes & decoration
- [x] constructor syntax & decoration
- [x] new type: `List`
- [x] Subtype algo
- [x] Equality algo
- [x] TypeOf algo for constructor expressions
- [x] TypeOf algo for prop access
- [x] Assess algo for constructor expressions
- [x] Assess algo for prop access
