### ISSUE TITLE
Collections — Hashes

### ISSUE THREAD

**Issue by chharvey** [chharvey/counterpoint#78]
# Features
- [x] new generic type syntax: `Hash.<T>`
- [x] new explicit type syntax `[:T]`
- [x] new constructor syntax: `Hash.<T>([x= a, y= b])`, takes an optional record arg
	- allows empty hash
- no literal syntax

# TODO
- [x] type syntaxes & decoration
- [x] constructor syntax & decoration
- [x] new type: `Hash`
- [x] Subtype algo
- [x] Equality algo
- [x] TypeOf algo for constructor expressions
- [x] TypeOf algo for prop access
- [x] Assess algo for constructor expressions
- [x] Assess algo for prop access
